---
name: Lint GitHub Actions Workflows
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/actionlint.yaml
      - .github/workflows/*.ya?ml
      - .github/actionlint.yaml

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1.65.2
